name: C Program Workflow

# This tells GitHub WHEN to run the job
on: [push, pull_request]

jobs:
  John:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Compile Hello World
        run: gcc hello.c -o hello
        
      - name: Run Program
        run: ./hello
