name: C Build
on: [push]
jobs:
  run-code: # This is the name that will appear on the left instead of "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gcc hello.c -o hello
      - run: ./hello

